# Generated by Django 4.2 on 2023-04-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='hehehe', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
